### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by lunhui11** [coolxitech/AutoMihoyoBBS#10]
2022-10-31T17:04:48 INFO 正在为旅行者热心网友ikun进行签到...
Traceback (most recent call last):
  File "/ql/data/scripts/coolxitech_AutoMihoyoBBS/ql_main.py", line 11, in <module>
    status_code, message = main()
  File "/ql/data/scripts/coolxitech_AutoMihoyoBBS/main.py", line 97, in main
    genshin_message = genshin_help.sign_account()
  File "/ql/data/scripts/coolxitech_AutoMihoyoBBS/genshin.py", line 117, in sign_account
    if data["data"] != "" and data.get("data").get("success", -1):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by coolxitech** [comment]
重新拉取
