### ISSUE TITLE
Docker无法使用

### ISSUE THREAD

**Issue by Canary233** [coolxitech/AutoMihoyoBBS#7]
`2022-10-30T11:22:56 INFO 使用DOCKER运行米游社签到

2022-10-30T11:22:56 INFO Starting signing

Traceback (most recent call last):

  File "/var/app/./main_multi.py", line 3, in <module>

    import main

  File "/var/app/main.py", line 4, in <module>

    import auto_cookie

  File "/var/app/auto_cookie.py", line 9, in <module>

    from Crypto.Cipher import PKCS1_v1_5

ModuleNotFoundError: No module named 'Crypto'

2022-10-30T11:22:56 INFO Current running datetime: 2022-10-30 11:22:56

2022-10-30T11:22:56 INFO Next run datetime: 2022-10-31 09:30:18`

已确认安装所有依赖,且使用`python3 main_multi.py`时可以正常运行.

**Comment by yriiolik** [comment]
要安装 gcc g++
然后安装 pycryptodome
